load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary", "scala_test")

package(default_visibility = ["//visibility:public"])

scala_library(
    name = "a",
    srcs = ["A.scala"],
    deps = [],
)
